### ISSUE TITLE
Laboratory not available

### ISSUE THREAD

**Issue by Phanthomas83** [Red-dog95/scotts-mods#1]
So i installed your mod.
But when i wanted to do some research, i wasn't able to build a laboratory, 'cause it needs the standard transport belts, which i can't build at the very beginning.

so, i have to uninstall it for now, do some research and hopefully can use it afterwards.

![part1](https://user-images.githubusercontent.com/1470448/50645195-3c5e9d00-0f73-11e9-8c45-634bd58f9498.png)
![part2](https://user-images.githubusercontent.com/1470448/50645196-3c5e9d00-0f73-11e9-8956-c52e1da234f9.png)

(sorry for bad english)

**Comment by Red-dog95** [comment]
I'm sorry this happened, I didn't check the recipe for the lab with is my fault. I'll have the mod updated as soon as possible. I foolishly tested the mod with all the recipes already unlocked so I must have missed this. 
Thanks for catching this error.

**Comment by Phanthomas83** [comment]
So, i did what i said.
deactivated your mod, produced and built a laboratory (no research done), reactivated the mod.

now, i don't know why, i can build lab's and normal belts without the neccessary research which was needed before ...

**Comment by Red-dog95** [comment]
I've just uploaded the new version of the mod. Since the "normal" transport belt needs to be unlocked through research, reactivating the mod likely replaced the modded tech recipes with the base game. It's only 1 technology that has been skipped (i think) so I don't think your save is ruined. You should be able to update the mod through the API and all should be well.

**Comment by Phanthomas83** [comment]
thanks, i will test it these days :-)
